[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"

[[main]]
    identifier = "previous-blog"
    name = "Archived Material"
    url = "https://archive.sleepymario.com/"

[[main]]
    identifier = "live-analytics"
    name = "Live Analytics"
    url = "https://analytics.sleepymario.com/"
